services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_posts_app
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME:-todouser}
      - DB_PASSWORD=${DB_PASSWORD:-todopassword}
      - DB_DATABASE=${DB_DATABASE:-todo_posts}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4318/v1/traces}
    depends_on:
      - mysql
      - redis
      - jaeger
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    container_name: todo_posts_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_DATABASE:-todo_posts}
      MYSQL_USER: ${DB_USERNAME:-todouser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-todopassword}
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: todo_posts_redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: todo_posts_jaeger
    ports:
      - '16686:16686' # Jaeger UI
      - '4318:4318' # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:16686']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data:
