services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo_posts_app
    ports:
      - '${PORT:-3000}:3000'
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT:-3306}
      - DB_USERNAME=${DB_USERNAME:-todouser}
      - DB_PASSWORD=${DB_PASSWORD:-todopassword}
      - DB_DATABASE=${DB_DATABASE:-todo_posts}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT:-6379}
      - OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT:-http://jaeger:4318/v1/traces}
    depends_on:
      - mysql
      - redis
      - jaeger
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: todo_posts_jaeger
    ports:
      - '16686:16686' # Jaeger UI
      - '4318:4318' # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  mysql:
    image: mysql:8.0
    container_name: todo_posts_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: ${DB_DATABASE:-todo_posts}
      MYSQL_USER: ${DB_USERNAME:-todouser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-todopassword}
    ports:
      - '${DB_PORT:-3306}:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    container_name: todo_posts_redis
    ports:
      - '${REDIS_PORT:-6379}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: todo_posts_prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:9090/-/healthy']
      interval: 10s
      timeout: 5s
      retries: 3

  grafana:
    image: grafana/grafana:latest
    container_name: todo_posts_grafana
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./config/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus
      - loki
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'localhost:3000/api/health']
      interval: 10s
      timeout: 5s
      retries: 3

  loki:
    image: grafana/loki:latest
    container_name: todo_posts_loki
    ports:
      - '3100:3100'
    volumes:
      - loki_data:/loki
      - ./config/loki/config.yaml:/etc/loki/config.yaml
    command:
      - '-config.file=/etc/loki/config.yaml'
      - '-validation.allow-structured-metadata=true'
      - '-config.expand-env=true'
    user: '0'
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - JAEGER_AGENT_PORT=6831
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1',
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      - jaeger

  promtail:
    image: grafana/promtail:latest
    container_name: todo_posts_promtail
    volumes:
      - /var/log:/var/log
      - ./config/promtail/config.yml:/etc/promtail/config.yml
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki

volumes:
  mysql_data:
  prometheus_data:
  grafana_data:
  loki_data:
