auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

common:
  path_prefix: /loki
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2023-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m

limits_config:
  retention_period: 744h  # 31 days
  max_global_streams_per_user: 5000
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6
  max_entries_limit_per_query: 5000
  max_label_name_length: 1024
  max_label_value_length: 2048
  allow_structured_metadata: true

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true

frontend:
  compress_responses: true
  log_queries_longer_than: 10s

analytics:
  reporting_enabled: false