name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run tests against'
        required: true
        default: 'development'
        type: choice
        options:
          - development
          - staging
          - production
      debug-enabled:
        description: 'Run the workflow with debug logging'
        required: false
        type: boolean
        default: false

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: todo_posts
          MYSQL_USER: todouser
          MYSQL_PASSWORD: todopassword
          MYSQL_ROOT_PASSWORD: todopassword
        ports:
          - 3306:3306

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Run migrations
        run: pnpm run migration:run
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: todouser
          DB_PASSWORD: todopassword
          DB_DATABASE: todo_posts

      - name: Run unit tests
        run: pnpm run test
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: todouser
          DB_PASSWORD: todopassword
          DB_DATABASE: todo_posts

      - name: Run e2e tests
        run: pnpm run test:e2e
        env:
          NODE_ENV: test
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_USERNAME: todouser
          DB_PASSWORD: todopassword
          DB_DATABASE: todo_posts
